spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #url: jdbc:p6spy:h2:~/bcmall-data/h2;MODE=MYSQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    url: jdbc:p6spy:h2:mem:test;MODE=MYSQL;CASE_INSENSITIVE_IDENTIFIERS=FALSE;DATABASE_TO_UPPER=false;
    #url: jdbc:p6spy:mysql://localhost:3306/bcmall?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round&useSSL=false&serverTimezone=GMT%2B8
    #username: root
    #password: root

logging:
  level:
    root: INFO
    org:
      apache:
        kafka: WARN
    com:
      github:
        xjjdog:
          bcmall: TRACE
